on:
  push:
    branches:
      - main

name: Deploy to Google App Engine

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm run install-dependencies

      - name: Test Webapp
        run: |
          npm test --prefix webapp -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Nest Backend
        run: npm run build --prefix backend

      - name: Build Angular Frontend
        run: npm run build --prefix webapp

      - name: Create .env file
        uses: SpicyPizza/create-envfile@master
        with:
          envkey_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          envkey_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          envkey_MONGODB_URL: ${{ secrets.MONGODB_URL }}
          envkey_PRODUCTION: true
          directory: backend
          file_name: .env

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Send telegram message about build status
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Build Status: {{job.status}}
